server:
  port: "8080"
clients:
  openai:
    key: 'some-key'
    embeddingmodal: 'some-key'
  gemini:
    key: 'some-key'
  superbase:
    url: 'some-key'
    key: 'some-key'
    endpointstablename: 'some-key'
    endpointoverridestablename: 'some-key'
    ingestionstablename: 'some-key'
    usagelogstablename: 'some-key'
  pinecone:
    key: 'some-key'
    indexhost: 'some-key'
